name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche le déploiement à chaque push sur la branche main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le dépôt
    - name: Checkout
      uses: actions/checkout@v3

    # Étape 2 : Installer Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Utilise la version de Node.js que tu utilises localement

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: npm install

    # Étape 4 : Générer le build
    - name: Build
      run: npm run build

    # Étape 5 : Déployer sur GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Déploie le contenu du dossier build